### ISSUE TITLE
Can't fade in Route(s) with react-inline-transition-group ( React-Router )

### ISSUE THREAD

**Issue by artfree** [felipethome/react-inline-transition-group#1]
I’m using react-inline-transition-group for, among other things, react-router transitions.  I’m using these settings & styles:  

          <Transition
                  childrenBaseStyle={this.styles['before']}
                  childrenEnterStyle={this.styles['enter']}
                  childrenAppearStyle={this.styles['appear']}
                  childrenLeaveStyle={this.styles['leave']}
                                                                                >
                 {React.cloneElement(this.props.children, {
                        key: this.props.location.pathname
                  })}                                                                 
         </Transition>

          this.styles['before']      = {opacity: '0'}
          this.styles['enter']        = {opacity: '1', transition: 'opacity 400ms'}
          this.styles['appear']     = {opacity: '1', transition: 'opacity 400ms'}
          this.styles['leave']        = {opacity: '0', transition: 'opacity 400ms'}

When transitioning routes, the new route appears (without fade in) while the old route fades out properly.

My question is: How can I fade in the new route rather than it appearing suddenly.   In other words, I want the new route to fade in while, simultaneously, the old route fades out.

**Comment by felipethome** [comment]
Hi @artfree , thanks for reporting. This was actually a problem with react-inline-transition-group and I fixed it in version 0.2.0.

**Comment by richardgorman** [comment]
Sorry to post on such an old issue, but it would be really great to have a complete working example of how to use this plugin with react-router.

Can either of you provide this? @felipethome @artfree

**Comment by felipethome** [comment]
Hi @richardgorman, can you open this as a separate issue? This way is easier for me to remember.

**Comment by artfree** [comment]
Hi richardgorman.  Sorry, but I don't have any examples.  felipethome is, I believe, the author, and would best be able to help you.  (I don't have any alternate solutions either.  I've moved away from React, entirely, in favor of Vue.js).
Good luck.

**Comment by richardgorman** [comment]
Thanks for the feedback. @felipethome I have opened a new issue, #7
