### ISSUE TITLE
Cannot change previous child's transition styles

### ISSUE THREAD

**Issue by richardgorman** [felipethome/react-inline-transition-group#10]
I am wondering if it currently possible to change the styles for previous children.

I can create different styles for each group of children that are inside the `<Transition>` but I want to be able to apply styling to previous children. I think that the plugin does not consider any previous children that have not 'left' when applying styles.

**Comment by felipethome** [comment]
I tested here and it seemed to work, but I just tested changing the appear/enter and base styles. How are you changing your previous styles?
