### ISSUE TITLE
Component element causing layout issues

### ISSUE THREAD

**Issue by fi5u** [felipethome/react-inline-transition-group#6]
The wrapping element is breaking some of my layouts. For example, if the parent of the transitioned element has `display: flex`, the transitioned element is no longer the direct child. Is it possible to have the ability to add inline styles to the `component` element?

**Comment by felipethome** [comment]
If you use the `style` property in the wrapper element like `<Transition style={...}>` you should be able to apply styles to it so you can make the wrapper `display: flex`.

**Comment by fi5u** [comment]
Yes, that solves the issue, thanks.
