### ISSUE TITLE
How to use with react-router?

### ISSUE THREAD

**Issue by richardgorman** [felipethome/react-inline-transition-group#7]
Hi, it would be great if there was an example of how to use this plugin correctly with react-router.

Currently, any transition that is added to the leaving route is not visible since react-router is not waiting for the transition to end before removing the route.

**Comment by felipethome** [comment]
Thanks @richardgorman, I will work on this as soon as possible! TransitionHooks (the underlying component of InlineTransitionGroup) should be the one removing components so the transitions can finish.

**Comment by richardgorman** [comment]
@felipethome Is there an actual issue with one of the plugins or is it just a matter of implementing it correctly?

**Comment by felipethome** [comment]
I'm not sure yet because I don't use ReactRouter so I will discover as soon as I make your example 😄 . Since of both of the components (ReactRouter and TransitionHooks) need to manage when a component is entering or leaving the UI maybe they will be incompatible, but this is the worst case scenario.

I believe there is a way of using the phase callbacks to synchronise them, or that is just an implementation detail. I will try to check this issue this weekend, so I can give you a better answer.

**Comment by felipethome** [comment]
The same example adapted to ReactInlineTransitionGroup:

```jsx
import React from 'react'
import Transition from 'react-inline-transition-group'
import { render } from 'react-dom'
import { browserHistory, Router, Route, IndexRoute, Link } from 'react-router'

import withExampleBasename from '../withExampleBasename'

const styles = {
  Image: {
    position: 'absolute',
    height: '400px',
    width: '400px'
  },

  base: {
    opacity: 0,
    transition: 'all 1000ms'
  },

  appear: {
    opacity: 1
  },

  leave: {
    opacity: 0
  }
}

const App = ({ children, location }) => (
  <div>
    <ul>
      <li><Link to="/page1">Page 1</Link></li>
      <li><Link to="/page2">Page 2</Link></li>
    </ul>

    <Transition
      component="div"
      childrenStyles={{
        base: styles.base,
        appear: styles.appear,
        enter: styles.appear,
        leave: styles.leave
      }}
    >
      {React.cloneElement(children, {
        key: location.pathname
      })}
    </Transition>
  </div>
)

const Index = () => (
  <div style={styles.Image}>
    <h1>Index</h1>
    <p>Animations with React Router are not different than any other animation.</p>
  </div>
)

const Page1 = (props) => (
  <div style={Object.assign({}, styles.Image, props.style)}>
    <h1>Page 1</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
)

const Page2 = (props) => (
  <div style={Object.assign({}, styles.Image, props.style)}>
    <h1>Page 2</h1>
    <p>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
)

render((
  <Router history={withExampleBasename(browserHistory, __dirname)}>
    <Route path="/" component={App}>
      <IndexRoute component={Index}/>
      <Route path="page1" component={Page1} />
      <Route path="page2" component={Page2} />
    </Route>
  </Router>
), document.getElementById('example'))
```

**Comment by richardgorman** [comment]
I updated my package and now it's working as expected.
Thanks!

**Comment by richardgorman** [comment]
Is it currently possible to apply different transitions to each Route? @felipethome

**Comment by felipethome** [comment]
I believe it is. You can try to check if the user is going backward or forward by any means that ReactRouter provides you (I know they pass parameters for the components so you can check the URL). Now that you know if you are going backward or forward you can apply the leaving styles conditionally.

Another thing that maybe is important for you to know is that my policy to update the styles when they change after the component is mounted is to update each of the children already inside the group.

**Comment by richardgorman** [comment]
I have tried to do this unsuccessfully. Could you please update your example from above to reflect what you mean?

**Comment by felipethome** [comment]
Sure, I will try to give you an example soon!
In the meantime can you please open another issue for this? Applying the styles conditionally is a question that maybe other people will have so this way it is easier for them to find the answer in the future.

**Comment by richardgorman** [comment]
Sure, no problem. I'll close this issue now.
